<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_menu().
 */
function moon_core_menu() {
  $items['admin/config/general_moon_settings'] = [
    'title' => 'Global MOON Settings',
    'type' => MENU_LOCAL_TASK,
    'description' => "Configure your sitewide MOON settings.",
    'page callback' => 'drupal_get_form',
    'page arguments' => ['moon_core_admin_form'],
    'access arguments' => ['administer nodes'],
    'file' => 'moon_core.admin.inc',
    'weight' => 5,
  ];

  return $items;
}

/**
 * Implements hook_node_view().
 */
function moon_core_node_view($node, $view_mode) {

  if ($node->type != 'photo') {
    return;
  }

  switch ($view_mode) {
    case 'teaser':
      if (!empty($node->field_image_multiple[LANGUAGE_NONE])) {
        foreach ($node->content['field_image_multiple'] as $key => $value) {
          if (is_int($key) && $key > 0) {
            unset($node->content['field_image_multiple'][$key]);
          }
        }
      }
      break;
  }
}

/**
 * Implements hook_preprocess_field().
 *
 * Manage image style for individual image.
 */
function moon_core_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] == 'field_image_multiple') {

    // Photo node.
    if (!empty($variables['element']['#object']) && $variables['element']['#object']->type == 'photo') {
      // Push the styles according to our rule..
//      foreach ($variables['items'] as $key => $img) {
//
//        if (($key == 0) || ((($key + 1) % 3) == 1)) {
//          continue;
//        }
//        $variables['items'][$key]['#image_style'] = 'photo_half_width';
//      }

      // Detect and Push the data about current page into JavaScript in
      // order to make the menu items active.
      // @group: ActiveItem
      $node = $variables['element']['#object'];

      $photo_type_array = field_get_items('node', $node, 'field_photo_type');

      // Default value.
      $active_type = 'all';

      if (!empty($photo_type_array)) {
        $all_term_tid = 5;
        foreach ($photo_type_array as $item) {
          if ($item['tid'] != $all_term_tid) {
            $term = taxonomy_term_load($item['tid']);
            $active_type = strtolower($term->name);
            break;
          }
        }
      }

      _moon_add_menu_data_js('photo', $active_type);
    }
  }
}

function _moon_add_menu_data_js($main = '', $secondary = '') {
  drupal_add_js(array(
    'activeMenuItem' => array(
      'mainMenuItem' => $main,
      'secondaryMenuItem' => $secondary,
    )
  ), array(
    'type' => 'setting'
  ));
}


/**
 * Implements hook_block_info().
 */
function moon_core_block_info() {
  $blocks = [];

  $blocks['moon_social'] = [
    'info' => t('Moon social block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  ];

  $blocks['moon_footer_contact'] = [
    'info' => t('Moon Footer Contact'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  ];
  $blocks['moon_contact_page_top'] = [
    'info' => t('Contact Page Top'),
    'cache' => DRUPAL_NO_CACHE,
  ];

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function moon_core_block_view($delta = '') {
  $block = [];

  switch ($delta) {
    case 'moon_social':
      $vars = _moon_core_get_social_data();
      $block['content'] = theme('moon_social', $vars);
      break;

    case 'moon_footer_contact':
      $footer_contact = variable_get('moon_phone');
      if ($footer_contact) {
        $block['content'] = '<div id="wrapp-footer_contact">' . $footer_contact . '</div>';
      }
      break;

    case 'moon_contact_page_top':
      $vars['tel_1'] = variable_get('moon_contact_page_top_tel_1');

      // At least 
      if (!empty($vars['tel_1']) || !empty($vars['email'])) {
        $vars['tel_2'] = variable_get('moon_contact_page_top_tel_2');
        $vars['email'] = variable_get('moon_contact_page_top_email');

        // Detect Mobile devices.
        require_once drupal_get_path('module', 'moon_core') . '/includes/Mobile_Detect.php';
        $detect = new Mobile_Detect;
        $vars['is_mobile'] = $detect->isMobile();

        $block['title'] = t('Contact Us');
        $block['content'] = theme('moon_contact_page_top', $vars);
      }
      break;
  }

  return $block;
}

/**
 * Helper function to retrieve the social buttons data.
 *
 * @todo Re-thing the logic. Be beautiful.
 */
function _moon_core_get_social_data() {
  static $vars = [];
  if (!empty($vars)) {
    return $vars;
  }
  $footer_vars = [
    'twitter_site_url',
    'fb_site_url',
    'instagram_site_url',
  ];

  foreach ($footer_vars as $var_name) {
    $vars[$var_name] = variable_get($var_name, FALSE);
  }
  $vars['social_count'] = count($vars);

  return $vars;
}

/**
 * Implements hook_theme().
 */
function moon_core_theme($existing, $type, $theme, $path) {
  return array(
    'moon_social' => array(
      'template' => 'moon-social',
      'arguments' => array('vars' => NULL),
      'path' => $path . '/theme',
    ),
    'moon_contact_page_top' => array(
      'template' => 'moon-contact-page-top',
      'arguments' => array('vars' => NULL),
      'path' => $path . '/theme',
    ),
  );
}

/* Examples */

//function HOOK_form_alter(&$form, &$form_state, $form_id);

function HOOK_preprocess_views_view(&$vars) {
  $view = &$vars['view'];
  if ($view->name == 'main_list' && $view->current_display == 'main_list') {
    //dsm($view, 'main list view');
  }
}
