<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_menu().
 */
function moon_core_menu() {
  $items['admin/config/general_moon_settings'] = [
    'title' => 'Global MOON Settings',
    'type' => MENU_LOCAL_TASK,
    'description' => "Configure your sitewide MOON settings.",
    'page callback' => 'drupal_get_form',
    'page arguments' => ['moon_core_admin_form'],
    'access arguments' => ['administer nodes'],
    'file' => 'moon_core.admin.inc',
    'weight' => 5,
  ];

//  $items['node/get/ajax/%/%'] = array(
//    'page callback' => '_xgaby_core_node_get_ajax',
//    'page arguments' => array(3, 4),
//    'type' => MENU_CALLBACK,
//    'access arguments' => array('access content'),
//  );

  return $items;
}

function _xgaby_core_node_get_ajax($nid, $view_mode) {
  // Add no-store in Cache-Control.
  drupal_add_http_header(
    'Cache-Control', 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', FALSE
  );
  // Hack for Safari
  #drupal_add_js('jQuery(window).unload(function(){});', array('type' => 'inline'));
  $node = node_load($nid);
  if ($node) {
    $node_view = node_view($node, $view_mode);
    print drupal_render($node_view);
    drupal_page_footer();
    return;
  }
  drupal_not_found();
}

/**
 * Implements hook_node_view().
 */
function moon_core_node_view($node, $view_mode) {

  if ($node->type != 'photo') {
    return;
  }

  switch ($view_mode) {
    case 'teaser':
      if (!empty($node->field_image_multiple[LANGUAGE_NONE])) {
        foreach ($node->content['field_image_multiple'] as $key => $value) {
          if (is_int($key) && $key > 0) {
            unset($node->content['field_image_multiple'][$key]);
          }
        }
      }
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function moon_core_block_info() {
  $blocks = array();

  $blocks['moon_social'] = array(
    'info' => t('Moon social block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['moon_footer_contact'] = array(
    'info' => t('Moon Footer Contact'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function moon_core_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'moon_social':
      $vars = _moon_core_get_social_data();
      $block['content'] = theme('moon_social', $vars);
      break;

    case 'moon_footer_contact':
      $mini_footer = variable_get('moon_phone');
      if ($mini_footer) {
        $block['content'] = '<div id="wrapp-footer_contact">' . $mini_footer . '</div>';
      }
      break;
  }

  return $block;
}

/**
 * Helper function to retrieve the social buttons data.
 *
 * @todo Re-thing the logic. Be beautiful.
 */
function _moon_core_get_social_data() {
  static $vars = [];
  if (!empty($vars)) {
    return $vars;
  }
  $footer_vars = [
    'twitter_site_url',
    'fb_site_url',
    'instagram_site_url',
  ];

  foreach ($footer_vars as $var_name) {
    $vars[$var_name] = variable_get($var_name, FALSE);
  }
  $vars['social_count'] = count($vars);

  return $vars;
}

/**
 * Implements hook_theme().
 */
function moon_core_theme($existing, $type, $theme, $path) {
  return array(
    'moon_social' => array(
      'template' => 'moon-social',
      'arguments' => array('vars' => NULL),
      'path' => $path . '/theme',
    ),
  );
}

#function fibonacci() {
#    $last = 0;
#    $current = 1;
#    yield 1;
#    while (true) {
#        $current = $last + $current;
#        $last = $current - $last;
#        yield $current;
#    }
#}

function HOOK_preprocess_page(&$variables) {

  // Add header variables for usage in page.tpl.php file.
  if ($header_line_1 = variable_get('header_line_1')) {
    $variables['header_line_1'] = $header_line_1;
  }
  if ($header_line_2 = variable_get('header_line_2')) {
    $variables['header_line_2'] = $header_line_2;
  }
}

//function HOOK_form_alter(&$form, &$form_state, $form_id);

function HOOK_preprocess_views_view(&$vars) {
  $view = &$vars['view'];
  if ($view->name == 'main_list' && $view->current_display == 'main_list') {
    //dsm($view, 'main list view');
  }
}
